openapi: 3.0.1
info:
  title: Washop/Admin/Base
  version: 1.1.0
servers:
- url: https://api.admin.wabow.com/
paths:
  /dummy:
    patch:
      tags:
      - 假功能
      summary: 假功能
      responses:
        200:
          $ref: '#/components/responses/UpdateOk'
        401:
          $ref: '#/components/responses/AuthError'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
components:
  parameters:
    Page:
      name: page
      in: query
      description: 指定頁數 (預設 1)
      schema:
        type: integer
    PerPage:
      name: per_page
      in: query
      description: 每頁返回的紀錄數量 (預設 20)
      schema:
        type: integer
    SortWay:
      name: sort_way
      in: query
      description: 排序方向
      schema:
        type: string
        enum:
        - asc
        - desc
        default: asc
    Otp:
      name: otp
      in: query
      description: 二次驗證碼 (6 碼數字，可能 0 開頭)
      required: true
      schema:
        $ref: '#/components/schemas/Otp'
    StartDate:
      name: start_date
      in: query
      description: 開始日期
      schema:
        type: string
        format: date
    EndDate:
      name: end_date
      in: query
      description: 結束日期
      schema:
        type: string
        format: date
    Tags:
      name: tags
      in: query
      description: 搜尋 標籤名稱 陣列
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/Tags'
    TagWay:
      name: tag_way
      in: query
      description: 標籤搜尋方式
      schema:
        type: string
        enum:
        - all
        - any
        default: any
    Cellphone:
      name: cellphone
      in: query
      description: 搜尋 手機號碼
      schema:
        type: string
    Email:
      name: email
      in: query
      description: 搜尋 Email
      schema:
        type: string
    Name:
      name: name
      in: query
      description: 搜尋 名稱 (姓名)
      schema:
        type: string
    StudentName:
      name: student_name
      in: query
      description: 搜尋 學員名稱 (姓名)
      schema:
        type: string
    EducationCode:
      name: education_code
      in: query
      description: 搜尋 教育年級
      schema:
        type: string
    PaymentCode:
      name: payment_code
      in: query
      description: 搜尋 金流
      schema:
        type: string
    SchoolCode:
      name: school_code
      in: query
      description: 搜尋 校區 (在班生)
      schema:
        type: string
  schemas:
    AuthError:
      type: object
      properties:
        exception:
          type: string
          description: 錯誤種類
          example: Illuminate\Auth\AuthenticationException
        message:
          type: string
          description: 錯誤訊息
          example: 身分認證無效
    Forbidden:
      type: object
      properties:
        exception:
          type: string
          description: 錯誤種類
          example: Illuminate\Auth\Access\AuthorizationException
        message:
          type: string
          description: 錯誤訊息
          example: 帳號無此權限
    FormError:
      type: object
      properties:
        exception:
          type: string
          description: 錯誤種類
          example: Illuminate\Validation\ValidationException
        message:
          type: string
          description: 錯誤訊息
          example: The given data was invalid.
        extra:
          type: object
          properties: {}
          description: 詳細錯誤訊息
          example:
          - email:
            - The email field is required.
          - password:
            - The password field is required.
    LoginFail:
      type: object
      properties:
        exception:
          type: string
          description: 錯誤種類
          example: Illuminate\Auth\AuthenticationException
        message:
          type: string
          description: 錯誤訊息
          example: 帳號或密碼錯誤。
    NotFound:
      type: object
      properties:
        exception:
          type: string
          description: 錯誤種類
          example: Illuminate\Database\Eloquent\ModelNotFoundException
        message:
          type: string
          description: 錯誤訊息
          example: Invalid data.
    OtpError:
      type: object
      properties:
        exception:
          type: string
          description: 錯誤種類
          example: Washop\Admin\Common\Exceptions\OtpException
        message:
          type: string
          description: 錯誤訊息
          example: The 2fa field is required.
    Ok:
      type: object
      properties:
        message:
          type: string
          description: 應用互動訊息
          example: ok
    Admin:
        allOf:
        - $ref: '#/components/schemas/Prefix'
        - type: object
          properties:
            name:
              type: string
              example: Admin
    Attrs:
      type: object
      properties:
        enable:
          type: boolean
          description: 上架 / 下架
          example: true
    BaseStatus:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
    Department:
      description: 部門
      allOf:
      - $ref: '#/components/schemas/BaseStatus'
      - example:
          code: guting-primary-school
          name: 古亭國小
    Education:
      description: 教育程度 & 年級
      allOf:
      - $ref: '#/components/schemas/BaseStatus'
      - example:
          code: high-school-1
          name: 高中一年級
    OrderStatus:
      description: 訂單狀態
      allOf:
      - $ref: '#/components/schemas/BaseStatus'
      - example:
          code: new
          name: 新名單
    Payment:
      description: 金流
      allOf:
      - $ref: '#/components/schemas/BaseStatus'
      - example:
          code: credit-card,
          name: 信用卡
    School:
      description: 校區
      allOf:
      - $ref: '#/components/schemas/BaseStatus'
      - example:
          code: guting
          name: 古亭
    OneThird:
      type: string
      enum:
      - y
      - n
      - x
      description: 三選一
      example: y
    Otp:
      type: string
      description: 二次驗證碼 (6 碼數字，可能 0 開頭)
      example: "085449"
    Datetime:
      type: string
      format: datetime
      example: "2021-01-29T03:16:42.000000Z"
    Image:
      type: object
      description: 圖檔
      properties:
        image:
          type: object
          properties:
            id:
              type: integer
              example: 1
            url:
              type: string
              description: 圖檔連結
              example: https://cdn/image/xxx.webp
    Birthday:
      type: object
      properties:
        birthday:
          type: string
          format: date
          description: 學員生日
          example: 1911-01-01
    Kinship:
      type: object
      properties:
        kinship:
          type: string
          description: 與學員關係
          example: 父子
    MaskName:
      type: object
      properties:
        mask_name:
          type: string
          description: 姓名 (遮罩)
          example: M***y
    MaskCellphone:
      type: object
      properties:
        mask_cellphone:
          type: string
          description: 手機號碼 (遮罩)
          example: 0912***678
    RawName:
      type: object
      properties:
        raw_name:
          type: string
          description: 姓名 (明碼)
          example: Marty
    RawCellphone:
      type: object
      properties:
        raw_cellphone:
          type: string
          description: 手機號碼 (明碼)
          example: 0912345678
    MaskContact:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - $ref: '#/components/schemas/Kinship'
      - $ref: '#/components/schemas/MaskName'
      - $ref: '#/components/schemas/MaskCellphone'
      - $ref: '#/components/schemas/Suffix'
    RawContact:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - $ref: '#/components/schemas/Kinship'
      - $ref: '#/components/schemas/RawName'
      - $ref: '#/components/schemas/RawCellphone'
      - $ref: '#/components/schemas/Suffix'
    MaskStudent:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - $ref: '#/components/schemas/Birthday'
      - $ref: '#/components/schemas/MaskName'
      - type: object
        properties:
          mask_identification:
            type: string
            description: 學員身分證
            example: A123***789
          education:
            $ref: '#/components/schemas/Education'
          comment:
            type: string
            description: 備註
            example: 備註...
          student_schools:
            type: array
            description: 【外生】此欄位無 或 空陣列
            items:
              $ref: '#/components/schemas/School'
      - $ref: '#/components/schemas/Suffix'
    RawStudent:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - $ref: '#/components/schemas/Birthday'
      - type: object
        properties:
          raw_name:
            type: string
            description: 學員姓名
            example: Marty
          raw_identification:
            type: string
            description: 學員身分證
            example: A123456789
          education:
            $ref: '#/components/schemas/Education'
          comment:
            type: string
            description: 備註
            example: 備註...
          student_schools:
            type: array
            description: 【外生】此欄位無 或 空陣列
            items:
              $ref: '#/components/schemas/School'
      - $ref: '#/components/schemas/Suffix'
    MaskUser:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - type: object
        properties:
          mask_email:
            type: string
            description: Email (遮罩)
            example: ma***@wabow.com
      - $ref: '#/components/schemas/MaskName'
      - $ref: '#/components/schemas/MaskCellphone'
    RawUser:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - type: object
        properties:
          raw_email:
            type: string
            description: Email (明碼)
            example: marty@wabow.com
      - $ref: '#/components/schemas/RawName'
      - $ref: '#/components/schemas/RawCellphone'
    MiniOrder:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - type: object
        properties:
          number:
            type: string
            description: 訂單編號
            example: '0000000202'
    ListOrder:
      allOf:
      - $ref: '#/components/schemas/MiniOrder'
      - type: object
        properties:
          group_id:
            type: integer
            description: 活動 ID
            example: 1
          group_name:
            type: string
            description: 活動名稱
            example: 升高中活動講座
          total:
            type: integer
            description: 含運總額
            example: 450
          admin_comment:
            type: string
            description: 客服備註
            example: ""
          admin:
            $ref: '#/components/schemas/Admin'
          department:
            $ref: '#/components/schemas/Department'
          status:
            $ref: '#/components/schemas/OrderStatus'
          student_education:
            $ref: '#/components/schemas/Education'
          mask_user:
            $ref: '#/components/schemas/MaskUser'
          mask_student:
            $ref: '#/components/schemas/MaskStudent'
      - $ref: '#/components/schemas/Suffix'
    OrderItem:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - type: object
        properties:
          product:
            $ref: '#/components/schemas/MiniProduct'
          final_price:
            type: integer
            description: 成交價
            example: 450
          quantity:
            type: integer
            description: 成交數量
            example: 1
          user_answer:
            allOf:
            - description: 會員回覆參加意願
            - $ref: '#/components/schemas/OneThird'
    MiniProduct:
      allOf:
      - $ref: '#/components/schemas/Prefix'
      - type: object
        properties:
          name:
            type: string
            description: 場次名稱
            example: 場次一
          location:
            type: string
            description: 地址
            example: 古亭國小
          start_at:
            $ref: 'base.yaml#/components/schemas/Datetime'
    Link:
      type: object
      description: 連結設定
      properties:
        path:
          type: string
          description: 站內路徑 (path / url 二選一)
          example: ""
        url:
          type: string
          description: 外站連結 (path / url 二選一)
          example: https://other.web.url
        attrs:
          type: object
          properties:
            isBlank:
              type: boolean
              description: 是否開新頁
              example: true
    Pagination:
      type: object
      properties:
        total:
          type: integer
          description: 紀錄總數
          example: 1
        per_page:
          type: integer
          description: 每頁紀錄數量
          example: 20
    Prefix:
      type: object
      properties:
        id:
          type: integer
          example: 1
    Sort:
      type: object
      properties:
        sort:
          type: integer
          description: 排序
          example: 10000
    Suffix:
      type: object
      description: model 通用結尾
      properties:
        created_at:
          $ref: '#/components/schemas/Datetime'
        updated_at:
          $ref: '#/components/schemas/Datetime'
    SuffixWithSort:
      description: model 含排序通用結尾
      allOf:
      - $ref: '#/components/schemas/Sort'
      - $ref: '#/components/schemas/Suffix'
    Tags:
      description: 標籤陣列
      type: array
      items:
        type: string
      example:
      - 標籤 A
      - 標籤 B
  responses:
    DeleteOk:
      description: 成功刪除資料
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ok'
    UpdateOk:
      description: 成功更新資料
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ok'
    ExportOk:
      description: 匯出 CSV 檔案至下載中心 (欄位同列表)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ok'
    ImportOk:
      description: 匯入成功
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ok'
    AuthError:
      description: 未認證
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthError'
    Forbidden:
      description: 沒有權限
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Forbidden'
    FormError:
      description: 表單錯誤
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FormError'
    NotFound:
      description: 找不到指定的資料
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFound'
    OtpError:
      description: 2fa 錯誤
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OtpError'
